# Generated by Django 2.0.3 on 2018-03-16 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0007_auto_20180316_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nascimento',
            field=models.DateField(default=datetime.date(2018, 3, 16), verbose_name='Data de Nascimento'),
        ),
    ]
