# Generated by Django 2.0.3 on 2018-03-16 20:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0008_auto_20180316_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nascimento',
            field=models.DateField(default=datetime.datetime(2018, 3, 16, 20, 1, 7, 776862, tzinfo=utc), verbose_name='Data de Nascimento'),
        ),
    ]
