# Generated by Django 2.0.4 on 2018-04-08 13:32

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0005_auto_20180319_1732'),
        ('contas', '0014_auto_20180318_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pedais_agendados',
            field=models.ManyToManyField(blank=True, related_name='pedais_agendados', to='grupos.Pedal', verbose_name='Pedais Marcados'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Seu nome será usado para identifica-lo de forma única na plataforma', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(re.compile('/(?=^.{2,60}$)^[A-ZÀÁÂĖÈÉÊÌÍÒÓÔÕÙÚÛÇ][a-zàáâãèéêìíóôõùúç]+(?:[ ](?:das?|dos?|de|e|[A-Z][a-z]+))*$/'), 'Informe um nome de usuário válido', 'este valor deve conter apenas letras e espaços', 'invalid')], verbose_name='Nome ou email'),
        ),
    ]
