# Generated by Django 2.0.4 on 2018-05-08 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0018_auto_20180505_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='amigos',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='user',
            name='convites_enviados',
        ),
        migrations.RemoveField(
            model_name='user',
            name='convites_recebidos',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='meus_grupos',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nascimento',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pedais_agendados',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pedais_gratis',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rua',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tel_emergencia',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telefone',
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
