# Generated by Django 2.0.3 on 2018-03-18 13:19

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome do grupo')),
                ('slug', models.SlugField()),
                ('criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modificacao', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
            },
        ),
        migrations.CreateModel(
            name='Pedal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('hora', models.TimeField(blank=True, null=True, verbose_name='Hora')),
                ('concentracao', models.CharField(max_length=50, verbose_name='Encontro')),
                ('quilometragem', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Quilometragem')),
                ('destino', models.CharField(max_length=50, verbose_name='Destino')),
                ('info', models.TextField(verbose_name='Informações Adicinais')),
                ('nivel', models.CharField(choices=[('1', 'Iniciante'), ('1', 'Médio'), ('1', 'Avançado')], max_length=1, verbose_name='Nível de dificuldade')),
                ('terreno', models.CharField(choices=[('1', 'Terra'), ('2', 'Asfalto'), ('3', 'Misto')], max_length=1, verbose_name='Terreno')),
                ('criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modificacao', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.Grupos', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Pedal',
                'verbose_name_plural': 'Pedais',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
