# Generated by Django 2.0.3 on 2018-03-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0002_auto_20180318_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedal',
            name='concentracao',
            field=models.CharField(max_length=25, verbose_name='Encontro'),
        ),
        migrations.AlterField(
            model_name='pedal',
            name='destino',
            field=models.CharField(max_length=25, verbose_name='Destino'),
        ),
    ]
