# Generated by Django 2.0.3 on 2018-03-16 19:54

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_auto_20180316_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cep',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^(\\d{5})-(\\d{3})$'))], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nascimento',
            field=models.DateField(blank=True, verbose_name='Data de Nascimento'),
        ),
    ]
