# Generated by Django 2.0.3 on 2018-03-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_auto_20180316_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nascimento',
            field=models.DateField(null=True, verbose_name='Data de Nascimento'),
        ),
    ]
