# Generated by Django 2.0.4 on 2018-06-13 20:35

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0025_auto_20180613_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Seu nome será usado para identifica-lo de forma única na plataforma', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$'), 'Informe um nome de usuário válido', 'este valor deve conter apenas letras e espaços', 'invalid')], verbose_name='nome'),
        ),
    ]
