# Generated by Django 2.0.4 on 2018-05-08 14:10

import annoying.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0019_auto_20180508_1002'),
        ('grupos', '0005_auto_20180319_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.URLField(blank=True)),
                ('sexo', models.CharField(blank=True, choices=[('1', 'Masculino'), ('2', 'Feminino')], max_length=1, null=True, verbose_name='Sexo')),
                ('nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('telefone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(re.compile('^[(\\.](\\d{2})[)\\.]?(\\d{4,5})[-\\.]?(\\d{4})$'))], verbose_name='Telefone')),
                ('tel_emergencia', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(re.compile('^[(\\.](\\d{2})[)\\.]?(\\d{4,5})[-\\.]?(\\d{4})$'))], verbose_name='Telefone de emergências')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^(\\d{3})\\.(\\d{3})\\.(\\d{3})-(\\d{2})$'))], verbose_name='CPF')),
                ('cep', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^(\\d{5})-(\\d{3})$'))], verbose_name='CEP')),
                ('rua', models.CharField(max_length=50, verbose_name='Endereço')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('estado', localflavor.br.models.BRStateField(max_length=2, verbose_name='Estado')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin')),
                ('amigos', models.ManyToManyField(blank=True, related_name='_profile_amigos_+', to='perfis.Profile', verbose_name='Meus Amigos')),
                ('convites_enviados', models.ManyToManyField(blank=True, related_name='_profile_convites_enviados_+', to='perfis.Profile', verbose_name='Convites Enviados')),
                ('convites_recebidos', models.ManyToManyField(blank=True, related_name='_profile_convites_recebidos_+', to='perfis.Profile', verbose_name='Convites Recebidos')),
                ('meus_grupos', models.ManyToManyField(blank=True, related_name='meus_grupos', to='grupos.Grupos', verbose_name='Meus Grupos')),
                ('pedais_agendados', models.ManyToManyField(blank=True, related_name='pedais_agendados', to='grupos.Pedal', verbose_name='Pedais Marcados')),
                ('pedais_gratis', models.ManyToManyField(blank=True, related_name='pedais_gratis', to='grupos.Pedal', verbose_name='Pedais Gratis')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
