# Generated by Django 2.0.4 on 2018-05-08 18:45

import django.core.validators
from django.db import migrations, models
import localflavor.br.models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bairro',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(re.compile('^(\\d{5})-(\\d{3})$'))], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cidade',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='estado',
            field=localflavor.br.models.BRStateField(blank=True, max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rua',
            field=models.CharField(blank=True, max_length=50, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tel_emergencia',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(re.compile('^[(\\.](\\d{2})[)\\.]?(\\d{4,5})[-\\.]?(\\d{4})$'))], verbose_name='Telefone de emergências'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(re.compile('^[(\\.](\\d{2})[)\\.]?(\\d{4,5})[-\\.]?(\\d{4})$'))], verbose_name='Telefone'),
        ),
    ]
