# Generated by Django 2.0.4 on 2018-06-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0003_profile_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nome',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome Completo'),
        ),
    ]
