# Generated by Django 2.0.4 on 2018-06-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0004_auto_20180607_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome Completo'),
        ),
    ]
