# Generated by Django 2.0.4 on 2018-06-13 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0005_auto_20180611_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rua',
        ),
    ]
