# Generated by Django 2.0.4 on 2018-06-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0006_auto_20180613_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='perfis', verbose_name='Foto'),
        ),
    ]
