# Generated by Django 2.0.4 on 2018-06-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0007_auto_20180616_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='perfis/foto', verbose_name='Foto'),
        ),
    ]
