# Generated by Django 2.0.4 on 2018-06-20 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0008_auto_20180616_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pedais_gratis',
        ),
    ]
