# Generated by Django 2.0.4 on 2018-06-20 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0009_remove_profile_pedais_gratis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='amigos',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='convites_enviados',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='convites_recebidos',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cpf',
        ),
    ]
