# Generated by Django 2.0.4 on 2018-06-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0016_pedal_publico'),
        ('perfis', '0010_auto_20180620_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='grupos_deletados',
            field=models.ManyToManyField(blank=True, related_name='grupos_deletados', to='grupos.Grupos', verbose_name='Grupos Deletados'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pedais_deletados',
            field=models.ManyToManyField(blank=True, related_name='pedais_deletados', to='grupos.Pedal', verbose_name='Pedais Excluidos'),
        ),
    ]
