# Generated by Django 2.0.4 on 2018-06-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0026_auto_20180629_0825'),
        ('perfis', '0011_auto_20180625_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='convites_de_grupo_recebidos',
            field=models.ManyToManyField(related_name='convites_de_grupo_recebidos', to='grupos.ConviteDeGrupo', verbose_name='Convites de Grupo'),
        ),
    ]
