# Generated by Django 2.0.4 on 2018-06-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0012_profile_convites_de_grupo_recebidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='convites_de_grupo_recebidos',
            field=models.ManyToManyField(blank=True, related_name='convites_de_grupo_recebidos', to='grupos.ConviteDeGrupo', verbose_name='Convites de Grupo'),
        ),
    ]
