# Generated by Django 2.0.3 on 2018-03-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupos',
            name='nome',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nome do grupo'),
        ),
    ]
