# Generated by Django 2.0.3 on 2018-03-19 20:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grupos', '0004_auto_20180318_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupos',
            name='admin',
        ),
        migrations.AddField(
            model_name='grupos',
            name='admin',
            field=models.ManyToManyField(related_name='admin', to=settings.AUTH_USER_MODEL, verbose_name='Administradores'),
        ),
    ]
