# Generated by Django 2.0.4 on 2018-06-14 09:32

from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0005_auto_20180319_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupos',
            name='cidade',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='grupos',
            name='estado',
            field=localflavor.br.models.BRStateField(blank=True, max_length=2, null=True, verbose_name='Estado'),
        ),
    ]
