# Generated by Django 2.0.4 on 2018-06-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0008_grupos_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupos',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo'),
        ),
    ]
