# Generated by Django 2.0.4 on 2018-06-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0009_grupos_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupos',
            name='publico',
            field=models.BooleanField(default=True, verbose_name='Privado'),
        ),
    ]
