# Generated by Django 2.0.4 on 2018-06-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0010_grupos_publico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupos',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='grupos/capas', verbose_name='Capa'),
        ),
        migrations.AlterField(
            model_name='grupos',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='grupos/logos', verbose_name='Logo'),
        ),
    ]
