# Generated by Django 2.0.4 on 2018-06-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0011_auto_20180616_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupos',
            name='publico',
            field=models.BooleanField(default=True, verbose_name='Público'),
        ),
    ]
