# Generated by Django 2.0.4 on 2018-06-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0012_auto_20180616_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedal',
            name='pago',
            field=models.BooleanField(default=False, verbose_name='Pedal Pago'),
        ),
    ]
