# Generated by Django 2.0.4 on 2018-06-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0013_pedal_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedal',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
