# Generated by Django 2.0.4 on 2018-06-24 20:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grupos', '0014_pedal_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedal',
            name='participantes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Participantes'),
        ),
    ]
