# Generated by Django 2.0.4 on 2018-06-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0015_pedal_participantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedal',
            name='publico',
            field=models.BooleanField(default=False, verbose_name='Público'),
        ),
    ]
