# Generated by Django 2.0.4 on 2018-06-25 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grupos', '0016_pedal_publico'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedal',
            name='criado_por',
            field=models.ForeignKey(limit_choices_to={'is_admin': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criador', to=settings.AUTH_USER_MODEL, verbose_name='Criador'),
        ),
    ]
