# Generated by Django 2.0.4 on 2018-06-25 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0018_auto_20180625_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedal',
            name='criado_por',
            field=models.ForeignKey(limit_choices_to={'is_admin': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criador', to='perfis.Profile', verbose_name='Criador'),
        ),
    ]
