# Generated by Django 2.0.4 on 2018-06-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0019_auto_20180625_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedal',
            name='participantes',
            field=models.ManyToManyField(related_name='participantes', to='perfis.Profile', verbose_name='Participantes'),
        ),
    ]
