# Generated by Django 2.0.4 on 2018-06-25 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0020_auto_20180625_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedal',
            old_name='criado_por',
            new_name='criador',
        ),
    ]
