# Generated by Django 2.0.4 on 2018-06-26 11:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0023_auto_20180625_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedal',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Preço'),
        ),
    ]
