# Generated by Django 2.0.4 on 2018-06-29 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perfis', '0011_auto_20180625_0857'),
        ('grupos', '0024_pedal_preco'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConviteDeGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, 'Pendente'), (2, 'Aceito'), (3, 'Regeitado')], default=1, verbose_name='Status')),
                ('criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('convidado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convidado', to=settings.AUTH_USER_MODEL, verbose_name='Convidado')),
                ('criador', models.ForeignKey(limit_choices_to={'is_admin': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criador_do_convite', to='perfis.Profile', verbose_name='Quem convidou')),
                ('grupo_que_convidou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo_que_convidou', to='grupos.Grupos', verbose_name='Grupo que convidou')),
            ],
            options={
                'verbose_name': 'Convite de Grupo',
                'verbose_name_plural': 'Convites de Grupo',
            },
        ),
    ]
