# Generated by Django 2.0.4 on 2018-06-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0025_convitedegrupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupos',
            name='convites_aguardando_aprovacao',
            field=models.ManyToManyField(related_name='convites_aguardando_aprovacao', to='grupos.ConviteDeGrupo', verbose_name='Convites Aguardando Aprovação'),
        ),
        migrations.AlterField(
            model_name='convitedegrupo',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pendente'), (1, 'Aceito'), (2, 'Aprovado'), (3, 'Regeitado')], default=0, verbose_name='Status'),
        ),
    ]
