# Generated by Django 2.0.4 on 2018-06-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0026_auto_20180629_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupos',
            name='convites_enviados',
            field=models.ManyToManyField(related_name='convites_enviados', to='grupos.ConviteDeGrupo', verbose_name='Convites Enviados'),
        ),
    ]
