# Generated by Django 2.0.4 on 2018-06-29 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0027_grupos_convites_enviados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convitedegrupo',
            name='criador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criador_do_convite', to='perfis.Profile', verbose_name='Quem convidou'),
        ),
    ]
