# Generated by Django 2.0.4 on 2018-06-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0029_auto_20180629_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupos',
            name='convites_aguardando_aprovacao',
            field=models.ManyToManyField(blank=True, related_name='convites_aguardando_aprovacao', to='grupos.ConviteDeGrupo', verbose_name='Convites Aguardando Aprovação'),
        ),
        migrations.AlterField(
            model_name='grupos',
            name='convites_enviados',
            field=models.ManyToManyField(blank=True, related_name='convites_enviados', to='grupos.ConviteDeGrupo', verbose_name='Convites Enviados'),
        ),
    ]
